service: squill
frameworkVersion: '^4.0.0'

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: d1bbuck3t 
  environment:
    STAGE: ${self:provider.stage}
  
  # Day 7: Production monitoring and tracing
  tracing:
    lambda: true
    apiGateway: true
  
  logs:
    restApi: true
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::squill-invoices-*/*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  ingestUsage:
    handler: handler.ingest_usage
    events:
      - http:
          path: usage
          method: post
          cors: true
  
  createCustomer:
    handler: handler.create_customer
    events:
      - http:
          path: customers
          method: post
          cors: true
  
  getCustomer:
    handler: handler.get_customer
    events:
      - http:
          path: customers/{customer_id}
          method: get
          cors: true
  
  updateCustomer:
    handler: handler.update_customer
    events:
      - http:
          path: customers/{customer_id}
          method: put
          cors: true
  
  getCustomerUsage:
    handler: handler.get_customer_usage
    events:
      - http:
          path: customers/{customer_id}/usage
          method: get
          cors: true
  
  createSubscription:
    handler: pricing_handlers.create_subscription
    events:
      - http:
          path: subscriptions
          method: post
          cors: true
  
  getSubscription:
    handler: pricing_handlers.get_subscription
    events:
      - http:
          path: subscriptions/{client_id}
          method: get
          cors: true
  
  calculatePricing:
    handler: pricing_handlers.calculate_pricing
    events:
      - http:
          path: pricing/calculate
          method: post
          cors: true
  
  updatePricingRules:
    handler: pricing_handlers.update_pricing_rules
    events:
      - http:
          path: pricing/rules/{client_id}
          method: put
          cors: true
  
  generateInvoice:
    handler: billing_handlers.generate_invoice
    events:
      - http:
          path: billing/generate
          method: post
          cors: true
  
  getInvoices:
    handler: billing_handlers.get_invoices
    events:
      - http:
          path: invoices/{customer_id}
          method: get
          cors: true
  
  getAnalytics:
    handler: billing_handlers.get_analytics
    events:
      - http:
          path: analytics
          method: get
          cors: true

resources:
  Resources:
    UsageEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsageEvents
        AttributeDefinitions:
          - AttributeName: customer_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: customer_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Customers
        AttributeDefinitions:
          - AttributeName: customer_id
            AttributeType: S
        KeySchema:
          - AttributeName: customer_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    SubscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Subscriptions
        AttributeDefinitions:
          - AttributeName: client_id
            AttributeType: S
        KeySchema:
          - AttributeName: client_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    PricingRulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PricingRules
        AttributeDefinitions:
          - AttributeName: client_id
            AttributeType: S
        KeySchema:
          - AttributeName: client_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    InvoicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Invoices
        AttributeDefinitions:
          - AttributeName: invoice_id
            AttributeType: S
        KeySchema:
          - AttributeName: invoice_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST